### ISSUE TITLE
Quick & dirty example available?

### ISSUE THREAD

**Issue by bastie** [exbin/deltahex-java#1]
Is a q&d example available to display the HexEd Panel with given File at a Swing JScrollPane?

thx

**Comment by hajdam** [comment]
Component contains it's own scroll panel.

On project's webpage there is simple example of the library usage https://bined.exbin.org/library/#usage

There is also almost single file editor example: https://github.com/exbin/bined-lib-java/blob/master/tools/bined-editor-basic/src/main/java/org/exbin/bined/editor/basic/BinEdEditorBasic.java

**Comment by bastie** [comment]
works fine thanks
