### ISSUE TITLE
How to change the starting address ?

### ISSUE THREAD

**Issue by FANGG3** [exbin/deltahex-java#2]

**Comment by hajdam** [comment]
Depending what you mean by this, you can either scroll to specific position after loading data / initializing (Ext)CodeArea:

`((ScrollingCapable) codeArea).setScrollPosition(new CodeAreaScrollPosition(long rowPosition, int rowOffset, int charPosition, int charOffset))`

Or if you mean that you want to show row position number starting not from zero but from other number, there is no good support for that and you'll have to make your own painter / copy of [DefaultCodeAreaPainter](https://github.com/exbin/bined-lib-java/blob/master/modules/bined-swing/src/main/java/org/exbin/bined/swing/basic/DefaultCodeAreaPainter.java) into your own class and increase dataPosition to desired value in method paintRowPosition and then attach this alternative painter with:

    CodeArea codeArea = new CodeArea();
    codeArea.setPainter(new YourCodeAreaPainter(codeArea));

**Comment by FANGG3** [comment]
Thank you for solving my problem, I was about to look for a hex component for my own decompiler, exbin is a good one.

**Comment by hajdam** [comment]
Other option to consider could be to use [ByteViewer](https://github.com/NationalSecurityAgency/ghidra/tree/master/Ghidra/Features/ByteViewer) hex component from [Ghidra SRE,](https://ghidra-sre.org) which has more capabilities for decompiler use case, namely multi selection, multi sections and synchronization with instructions list. BinEd library doesn't have such capabilities yet as it was focused more on data editing, but it would require more effort to extract ByteViewer out.
